### ISSUE TITLE
中文路径报错问题，0.0.6版本仍然报错

### ISSUE THREAD

**Issue by s544838371** [AndersonBY/vector-vein#12]
# 情况说明
之前06.03的时候打开0.0.4没问题，刚刚下载了0.0.5打开报错，然后再打开0.0.4报错，跟0.0.5报错内容一致，两个版本的文件分别存在不同名称的文件夹里
# 报错截图如下
![微信截图_20230605092340](https://github.com/AndersonBY/vector-vein/assets/40713819/42fb30ef-e12e-4602-bbaa-3b1a4eae21e2)
# 报错信息如下
```
Traceback (most recent call last):
  File "main.py", line 102, in <module>
  File "webview\__init__.py", line 132, in start
  File "webview\guilib.py", line 101, in initialize
  File "webview\guilib.py", line 62, in try_import
  File "webview\guilib.py", line 52, in import_winforms
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "webview\platforms\winforms.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 64, in __call__
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

**Comment by s544838371** [comment]
问题已解决，放在中文目录的问题，大佬是不是考虑加个提醒在README下
@AndersonBY

**Comment by AndersonBY** [comment]
> 问题已解决，放在中文目录的问题，大佬是不是考虑加个提醒在README下 @AndersonBY

我先加个提醒，不过我自己测试在中文路径是正常的，还得看看是什么问题

**Comment by s544838371** [comment]
> > 问题已解决，放在中文目录的问题，大佬是不是考虑加个提醒在README下 @AndersonBY
> 
> 我先加个提醒，不过我自己测试在中文路径是正常的，还得看看是什么问题

ok，我是最开始把文件夹放在D:\软件目录下的，移出来放到D:\下就没问题了

**Comment by s544838371** [comment]
> 初步怀疑是pythonnet的问题，我自己的windows系统应该是手动改过utf8编码的所以没报错

@AndersonBY 我看0.0.6版本修复了中文路径的问题？但是为啥我这里还是报错，给你贴个报错图
![微信截图_20230615084006](https://github.com/AndersonBY/vector-vein/assets/40713819/b59e0651-f3c8-4f9a-925d-cf07455b4edd)

**Comment by AndersonBY** [comment]
你试一下配个开发环境然后用开发模式打开看看是不是正常的？这样可以看问题是在打包还是就是pythonnet本身的问题。

**Comment by s544838371** [comment]
> 你试一下配个开发环境然后用开发模式打开看看是不是正常的？这样可以看问题是在打包还是就是pythonnet本身的问题。

好，我测试下

**Comment by s544838371** [comment]
> 你试一下配个开发环境然后用开发模式打开看看是不是正常的？这样可以看问题是在打包还是就是pythonnet本身的问题。

python3.8.17的安装包，求一个

**Comment by s544838371** [comment]
> 你试一下配个开发环境然后用开发模式打开看看是不是正常的？这样可以看问题是在打包还是就是pythonnet本身的问题。
@AndersonBY 
![image](https://github.com/AndersonBY/vector-vein/assets/40713819/3db768cd-572a-4933-97c9-c007e73f4f60)

**Comment by AndersonBY** [comment]
那看来还不是打包的问题 我研究一下是不是pythonnet的问题

**Comment by AndersonBY** [comment]
修好了，是clr_loader模块的问题，[https://github.com/pythonnet/clr-loader/issues/59#issuecomment-1594463222](https://github.com/pythonnet/clr-loader/issues/59#issuecomment-1594463222)

https://github.com/AndersonBY/vector-vein/releases/download/v0.0.7/vector-vein-windows-v0.0.7.zip
