### ISSUE TITLE
最新代码pdm install报错

### ISSUE THREAD

**Issue by s544838371** [AndersonBY/vector-vein#17]
@AndersonBY 
# 报错信息如下
```
PS D:\Git项目\vector-vein\backend> pdm install -v
Lock file hash doesn't match pyproject.toml, packages may be outdated
Updating the lock file...
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pywebview>=4.1
pdm.termui:   httpx>=0.22.0
pdm.termui:   peewee>=3.16.2
pdm.termui:   pypdf>=3.8.1
pdm.termui:   mammoth>=1.5.1
pdm.termui:   openpyxl>=3.1.2
pdm.termui:   python-pptx>=0.6.21
pdm.termui:   openai>=0.27.0
pdm.termui:   python-docx>=0.8.11
pdm.termui:   htmldocx>=0.0.7
pdm.termui:   pandas>=2.0.1
pdm.termui:   yagmail>=0.15.293
pdm.termui:   qdrant-client>=1.1.3
pdm.termui:   markdown2>=2.4.8
pdm.termui:   tiktoken>=0.4.0
pdm.termui:   pyinstaller>=5.11.0
pdm.termui:   readability-lxml>=0.8.1
pdm.termui:   markdownify>=0.11.6
pdm.termui:   yt-dlp>=2023.3.4
pdm.termui:   pycryptodome>=3.18.0
pdm.termui:   clr-loader @ git+https://github.com/AndersonBY/clr-loader.git
pdm.termui:   python>=3.8,<3.12
pdm.termui:   Adding requirement pywebview>=4.1
pdm.termui:   Adding requirement httpx>=0.22.0
pdm.termui:   Adding requirement peewee>=3.16.2
pdm.termui:   Adding requirement pypdf>=3.8.1
pdm.termui:   Adding requirement mammoth>=1.5.1
pdm.termui:   Adding requirement openpyxl>=3.1.2
pdm.termui:   Adding requirement python-pptx>=0.6.21
pdm.termui:   Adding requirement openai>=0.27.0
pdm.termui:   Adding requirement python-docx>=0.8.11
pdm.termui:   Adding requirement htmldocx>=0.0.7
🔒 Lock failed
Unable to find a resolution for htmldocx
Please make sure the package name is correct.
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\dongguodong\appdata\roaming\python\scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\dongguodong\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 289, in main
    return Core().main(args)
  File "C:\Users\dongguodong\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 207, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\dongguodong\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 202, in main
    self.handle(project, options)
  File "C:\Users\dongguodong\AppData\Roaming\pdm\venv\lib\site-packages\pdm\core.py", line 157, in handle
    command.handle(project, options)
  File "C:\Users\dongguodong\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\commands\install.py", line 84, in handle
    actions.do_lock(
  File "C:\Users\dongguodong\AppData\Roaming\pdm\venv\lib\site-packages\pdm\cli\actions.py", line 109, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
NativeCommandExitException: Program "pdm.exe" ended with non-zero exit code: 1.
```
# 主要报错内容
```
Unable to find a resolution for htmldocx
Please make sure the package name is correct.
```

**Comment by jiangfangfangxm** [comment]
在windows 安装开发环境时，遇到同样的问题：

PS D:\vector-vein-dev\vector-vein\backend> pdm -v install
Lock file does not exist
Updating the lock file...
  Lock failed
Unable to find a resolution for htmldocx
Please make sure the package name is correct.
See C:\Users\JIANGF~1\AppData\Local\Temp\pdm-lock-f28axxwk.log for detailed debug log.
[ResolutionImpossible]: Unable to find a resolution
Add '-v' to see the detailed traceback

**Comment by AndersonBY** [comment]
修好了，之前改pyproject.toml的时候把htmldocx的包版本不小心也改了。
