### ISSUE TITLE
求助：工作流运行错误

### ISSUE THREAD

**Issue by s544838371** [AndersonBY/vector-vein#18]
@AndersonBY 
# 报错信息截图
![报错截图](https://cdn.staticaly.com/gh/s544838371/picx-images-hosting@master/20230617/微信截图_20230617113420.5sqovgty8q40.png)
![数据库截图](https://cdn.staticaly.com/gh/s544838371/picx-images-hosting@master/20230617/微信截图_20230617114039.7kj60boqb7g0.webp)
# 情况说明
1. 选择数据库
2. 输入网址
3. 运行
4. 报错提示运行失败，出错任务：添加数据
5. 查看数据库：有抓取数据下来
# 相关输入信息
网址：https://sspai.com/post/80121
数据库：Chatgpt开源项目

**Comment by AndersonBY** [comment]
看看文件夹里的log文件夹，看看日志怎么写的报错

**Comment by s544838371** [comment]
@AndersonBY 

> 看看文件夹里的log文件夹，看看日志怎么写的报错
```
2023-06-17 23:41:50,207 - worker receive task
2023-06-17 23:41:51,959 - Traceback (most recent call last):
  File "worker\__init__.py", line 77, in main_worker
  File "worker\tasks\__init__.py", line 36, in __call__
  File "worker\tasks\__init__.py", line 33, in __call__
  File "worker\tasks\__init__.py", line 15, in __call__
  File "worker\tasks\vector_db.py", line 48, in add_data
  File "utilities\embeddings.py", line 22, in get_embedding_from_open_ai
  File "openai\api_resources\embedding.py", line 33, in create
  File "openai\api_resources\abstract\engine_api_resource.py", line 153, in create
  File "openai\api_requestor.py", line 298, in request
  File "openai\api_requestor.py", line 700, in _interpret_response
  File "openai\api_requestor.py", line 763, in _interpret_response_line
openai.error.AuthenticationError: <empty message>

2023-06-17 23:41:51,959 - main_worker error: <empty message>
2023-06-17 23:41:51,959 - error_task: add_data
2023-06-17 23:41:51,959 - error_module: vector_db
```

**Comment by AndersonBY** [comment]
openai.error.AuthenticationError: <empty message>
感觉是认证的问题吧，是不是API KEY之类的问题

**Comment by s544838371** [comment]
> openai.error.AuthenticationError: 感觉是认证的问题吧，是不是API KEY之类的问题

@AndersonBY  这个错误信息咋没捕获到？
```
<empty message>
```

**Comment by AndersonBY** [comment]
我测试了一下设置了OpenAI API Base之后是有设置的，你看看你那边是具体为什么没设置上

![image](https://github.com/AndersonBY/vector-vein/assets/3096131/38a43eed-a39d-46fd-b6b9-3dc35f5bb521)

**Comment by s544838371** [comment]
> 我测试了一下设置了OpenAI API Base之后是有设置的，你看看你那边是具体为什么没设置上
> 
> ![image](https://user-images.githubusercontent.com/3096131/246717795-38a43eed-a39d-46fd-b6b9-3dc35f5bb521.png)

@AndersonBY 大佬你在搞我，我根据报错信息查了下代码，结果你猜我发现了什么，你没调用openai_api_base啊，你这个地方没改啊，代码位置：backend\utilities\embeddings.py
代码如下：
```
def get_embedding_from_open_ai(text: str, setting: dict = None):
    openai.api_key = setting.get("openai_api_key")
    if setting.get("openai_api_type") == "azure":
        openai.api_type = "azure"
        openai.api_base = setting.get("openai_api_base")
        openai.api_version = "2022-12-01"
        engine = setting.get("openai_embedding_engine")
        return openai.Embedding.create(input=[text], engine=engine)["data"][0]["embedding"]
    else:
        openai.api_type = "open_ai"
        openai.api_base = "https://api.openai.com/v1"
        openai.api_version = None
        model = "text-embedding-ada-002"
        return openai.Embedding.create(input=[text], model=model)["data"][0]["embedding"]
```

**Comment by AndersonBY** [comment]
没注意这个地方，只看了llms.py，忘了embedding这边了……
改好了

**Comment by s544838371** [comment]
> 没注意这个地方，只看了llms.py，忘了embedding这边了…… 改好了

OK
