### ISSUE TITLE
今日最新版pdm run dev报错

### ISSUE THREAD

**Issue by s544838371** [AndersonBY/vector-vein#38]
# 操作步骤
1. 拉取代码https://github.com/AndersonBY/vector-vein.git
2. cd backend
3. pdm install
4. pdm run dev
# 报错信息
```
PS D:\git\vector-vein\backend> pdm run dev
2023-08-25 09:54:54,393 - unable to open database file
2023-08-25 09:54:54,393 - Proxies: {}
2023-08-25 09:54:54,393 - unable to open database file
2023-08-25 09:54:54,393 - Proxies for requests: {}
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    from worker import main_worker, main_vector_database
  File "D:\git\vector-vein\backend\worker\__init__.py", line 10, in <module>
    from utilities.workflow import Workflow
  File "D:\git\vector-vein\backend\utilities\workflow.py", line 111, in <module>
    class Workflow:
  File "D:\git\vector-vein\backend\utilities\workflow.py", line 146, in Workflow
    def handle_workflow_invoke(self, node_obj: Node) -> list[dict]:
TypeError: 'type' object is not subscriptable
NativeCommandExitException: Program "pdm.exe" ended with non-zero exit code: 1.
```
# 其他
pdm run build 在未删除文件夹重新down一份代码时报错如下：
```
PS D:\git\vector-vein\backend> pdm run build
Fatal error in launcher:
```
整个文件夹删除重新搞的时候是没问题的，不知道什么原因

**Comment by AndersonBY** [comment]
用了3.9的类型提示语法，改了，现在兼容3.8了
