### ISSUE TITLE
pdm install报错

### ISSUE THREAD

**Issue by xmy89929** [AndersonBY/vector-vein#39]
D:\myProjects\vector-vein-main\backend>pdm install -v
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Synchronizing working set with lock file: 57 to add, 25 to update, 0 to remove

pdm.termui: Removing distribution setuptools
pdm.termui: Error occurred during uninstallation, roll back the changes now.
pdm.termui: Can't rollback, not uninstalled yet
  ✖ Update setuptools 65.6.3 -> 68.1.2 failed
Traceback (most recent call last):
  File "D:\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\13328\.local\bin\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\13328\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 290, in main
    return Core().main(args or sys.argv[1:])
  File "C:\Users\13328\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\13328\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 203, in main
    self.handle(project, options)
  File "C:\Users\13328\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 157, in handle
    command.handle(project, options)
  File "C:\Users\13328\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\commands\install.py", line 95, in handle
    actions.do_sync(
  File "C:\Users\13328\.local\pipx\venvs\pdm\lib\site-packages\pdm\cli\actions.py", line 213, in do_sync
    synchronizer.synchronize()
  File "C:\Users\13328\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 433, in synchronize
    handlers[kind](key, progress)
  File "C:\Users\13328\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\synchronizers.py", line 303, in update_candidate
    self.manager.uninstall(dist)
  File "C:\Users\13328\.local\pipx\venvs\pdm\lib\site-packages\pdm\installers\manager.py", line 50, in uninstall
    raise UninstallError(e) from e
pdm.exceptions.UninstallError: [WinError 5] 拒绝访问。: 'd:\\anaconda3\\lib\\site-packages\\_distutils_hack\\override.py'

**Comment by AndersonBY** [comment]
你这个看起来是权限问题吧，管理员模式安装试试

**Comment by xmy89929** [comment]
> 你这个看起来是权限问题吧，管理员模式安装试试

啊是的 解决了 感谢大佬
