### ISSUE TITLE
最新版本（Sep 23) 启动后端开发服务报错

### ISSUE THREAD

**Issue by guancan** [AndersonBY/vector-vein#42]
## 报错信息
g******n@guancandeAir backend % pdm run dev
2023-10-12 16:32:30,341 - unable to open database file
2023-10-12 16:32:30,341 - Proxies: {}
2023-10-12 16:32:30,342 - unable to open database file
2023-10-12 16:32:30,342 - Proxies for requests: {}
Traceback (most recent call last):
  File "/Users/guancan/Documents/GitHub/vector-vein/backend/main.py", line 29, in <module>
    from worker import main_worker, main_vector_database
  File "/Users/guancan/Documents/GitHub/vector-vein/backend/worker/__init__.py", line 13, in <module>
    from worker.tasks import (
  File "/Users/guancan/Documents/GitHub/vector-vein/backend/worker/tasks/output.py", line 14, in <module>
    from htmldocx import HtmlToDocx
  File "/Users/guancan/Documents/GitHub/vector-vein/backend/.venv/lib/python3.9/site-packages/htmldocx/__init__.py", line 1, in <module>
    from .h2d import HtmlToDocx
  File "/Users/guancan/Documents/GitHub/vector-vein/backend/.venv/lib/python3.9/site-packages/htmldocx/h2d.py", line 25, in <module>
    from docx.oxml import OxmlElement
ImportError: cannot import name 'OxmlElement' from 'docx.oxml' (/Users/guancan/Documents/GitHub/vector-vein/backend/.venv/lib/python3.9/site-packages/docx/oxml/__init__.py)

## 解决尝试
尝试删除并重新拉取代码、重装 python-docx 包等方法，木有解决问题

**Comment by AndersonBY** [comment]
`pdm list --sort name`

贴一下各个库的版本，我看看

**Comment by AndersonBY** [comment]
我估计是这个问题：https://github.com/pqzx/html2docx/issues/61

但是这个库看起来不更新了，我看看要么 fork 一下要么换个库
