### ISSUE TITLE
pdm run dev报错

### ISSUE THREAD

**Issue by AIXiaoBaiDemon** [AndersonBY/vector-vein#48]
报错信息如下：
Traceback (most recent call last):
  File "E:\vector-vein\backend\main.py", line 22, in <module>
    from api.database_api import DatabaseAPI, DatabaseObjectAPI
  File "E:\vector-vein\backend\api\database_api.py", line 16, in <module>
    from utilities.web_crawler import crawl_text_from_url
  File "E:\vector-vein\backend\utilities\web_crawler.py", line 16, in <module>
    from readability import Document
  File "E:\vector-vein\backend\.venv\Lib\site-packages\readability\__init__.py", line 3, in <module>
    from .readability import Document
  File "E:\vector-vein\backend\.venv\Lib\site-packages\readability\readability.py", line 11, in <module>
    from .cleaners import clean_attributes
  File "E:\vector-vein\backend\.venv\Lib\site-packages\readability\cleaners.py", line 3, in <module>
    from lxml.html.clean import Cleaner
  File "E:\vector-vein\backend\.venv\Lib\site-packages\lxml\html\clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.

**Comment by AndersonBY** [comment]
你运行一下 `pdm update` 更新你的依赖吧

**Comment by AIXiaoBaiDemon** [comment]
更新了，依然是这个报错

**Comment by AndersonBY** [comment]
删掉 .venv 重新安装吧

**Comment by AIXiaoBaiDemon** [comment]
python用什么版本比较好？默认会下载3.12版本

**Comment by AndersonBY** [comment]
我目前开发是3.11，3.12的话我测一下

**Comment by AndersonBY** [comment]
简单测了一下3.12好像不太行，会改一下版本限制

**Comment by AIXiaoBaiDemon** [comment]
当我按照提示安装后项目可以正常运行了
pdm add lxml
pdm add lxml_html_clean

**Comment by AndersonBY** [comment]
更新依赖了
