### ISSUE TITLE
如何设置调用本地大模型，Ollama

### ISSUE THREAD

**Issue by Cynric-h-new** [AndersonBY/vector-vein#49]

**Comment by AndersonBY** [comment]
在设置里的本地大语言模型添加本地模型的API接口，只要是兼容OpenAI格式调用的都可以用，然后工作流节点里就可以拖本地语言模型节点出来选择模型用了

**Comment by Cynric-h-new** [comment]
[https://blog.csdn.net/walkskyer/article/details/137580129](url)
Ollama兼容OpenAI格式，但需要安装ollama的python库：

安装ollama Python库
首先，您需要确保已经安装了ollama的Python库。您可以通过以下命令安装：

pip install ollama
这个命令会从Python包管理器下载并安装ollama库及其依赖。

初始化客户端
使用ollama的OpenAI库非常直观。以下是一个简单的例子，展示了如何初始化ollama客户端：

from ollama import OpenAI

client = OpenAI(
    base_url='http://localhost:11434/v1/',
    api_key='ollama',  # 此处的api_key为必填项，但在ollama中会被忽略
)

在这个例子中，我们通过导入ollama库中的OpenAI类，并创建了OpenAI的一个实例。在实例化过程中，我们需要提供两个参数：base_url和api_key。base_url是ollama服务的基础URL，而api_key虽然在ollama中会被忽略，但出于兼容性考虑，仍然需要提供。

**Comment by AndersonBY** [comment]
https://github.com/AndersonBY/vector-vein/releases/download/v0.1.5/vector-vein-windows-v0.1.5.zip

用最新版本，然后 APIBase 就填 http://localhost:11434/v1/ API Key 填 ollama

添加一个模型，然后填模型ID，确保和你运行ollma指令时那个一样，比如
`ollama run qwen:0.5b-chat-v1.5-q2_K`
那模型ID就是 **qwen:0.5b-chat-v1.5-q2_K**

**Comment by Cynric-h-new** [comment]
下了最新版本，调用失败：

2024-05-09 10:09:32,326 - Proxies: {}
2024-05-09 10:09:32,326 - Proxies for requests: {}
2024-05-09 10:09:32,859 - Debug: False
2024-05-09 10:09:32,859 - Version: 0.1.5
2024-05-09 10:09:32,861 - Task worker start
2024-05-09 10:09:33,581 - Vector database worker start
2024-05-09 10:09:51,417 - worker receive task
2024-05-09 10:09:51,421 - Traceback (most recent call last):
  File "worker\__init__.py", line 82, in main_worker
  File "worker\tasks\__init__.py", line 39, in __call__
  File "worker\tasks\__init__.py", line 36, in __call__
  File "worker\tasks\__init__.py", line 18, in __call__
  File "worker\tasks\__init__.py", line 68, in wrapper
  File "worker\tasks\llms\__init__.py", line 61, in local_llm
  File "worker\tasks\llms\local_llm.py", line 28, in __init__
AttributeError: 'NoneType' object has no attribute 'get'

2024-05-09 10:09:51,422 - main_worker error: 'NoneType' object has no attribute 'get'
2024-05-09 10:09:51,422 - error_task: local_llm
2024-05-09 10:09:51,422 - error_module: llms

**Comment by Cynric-h-new** [comment]
成功了，谢谢，之前不知道为什么出错。
