### ISSUE TITLE
建议提供docker部署能力

### ISSUE THREAD

**Issue by steelli** [AndersonBY/vector-vein#5]
我macOS，项目克隆下来之后，执行pdm install命令报错：

Unable to find a resolution for pyinstaller
Please make sure the package name is correct.
Traceback (most recent call last):
  File "/opt/homebrew/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Cellar/pdm/1.15.3/libexec/lib/python3.10/site-packages/pdm/core.py", line 232, in main
    return Core().main(args)
  File "/opt/homebrew/Cellar/pdm/1.15.3/libexec/lib/python3.10/site-packages/pdm/core.py", line 167, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/opt/homebrew/Cellar/pdm/1.15.3/libexec/lib/python3.10/site-packages/pdm/core.py", line 162, in main
    f(options.project, options)
  File "/opt/homebrew/Cellar/pdm/1.15.3/libexec/lib/python3.10/site-packages/pdm/cli/commands/install.py", line 48, in handle
    actions.do_lock(project, strategy=strategy, dry_run=options.dry_run)
  File "/opt/homebrew/Cellar/pdm/1.15.3/libexec/lib/python3.10/site-packages/pdm/cli/actions.py", line 114, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution

已经折腾了半天了，目前问题仍然无法解决，第一步的环境问题就卡主了，建议提供docker部署能力，避免让大家折腾环境问题。

**Comment by AndersonBY** [comment]
<img width="1280" alt="image" src="https://github.com/AndersonBY/vector-vein/assets/3096131/5b6b4aed-8784-4265-9714-070a86e1ccfa">
我这里用python3.8是OK的，你换到3.8试试吧。由于pywebview的原因，目前还是以3.8为主

**Comment by steelli** [comment]
macOS下切到python3.8 能跑起来，前端页面可以打开，不过Tab切换到"官方工作流模板"的时候，后端服务直接挂掉，报如下错误：
 Terminating app due to uncaught exception 'OC_PythonException', reason: '<class 'ModuleNotFoundError'>: No module named 'Security''

看项目源码，貌似是依赖的webview有问题，
<img width="1408" alt="image" src="https://github.com/AndersonBY/vector-vein/assets/1320387/33d74202-e34e-4103-84e0-26359c1c28d3">
不知道这个问题应该怎么解决。

**Comment by AndersonBY** [comment]
更新了一下pyproject.toml，你拉取最新的版本然后运行`pdm install -G mac`试试，按照pywebview里的提示需要单独给Mac装pyobjc模块

**Comment by AndersonBY** [comment]
更新了一下pyproject.toml，你拉取最新的版本然后运行`pdm install -G mac`试试，按照pywebview里的提示需要单独给Mac装pyobjc模块

**Comment by steelli** [comment]
最新版本上的lock文件貌似没有更新，执行pdm install -G mac命令提示如下：
Requested groups not in lockfile: mac

**Comment by AndersonBY** [comment]
我把pdm.lock去掉不跟踪了 怕跨平台依赖不同的问题。你删掉你的pdm.lock重新安装一次试试

**Comment by AndersonBY** [comment]
> 赞同，应该提供docker部署

这是单机程序，用的pywebview，虽然本质上前后端有分离但是pywebview在中间做了很多处理不是简单就能拆成纯浏览器/服务器架构的，所以除非有更更简便的方法，否则暂时不会往这块去做。
