### ISSUE TITLE
已有流程在新的 V0.2.10上无法运行

### ISSUE THREAD

**Issue by suepradun** [AndersonBY/vector-vein#66]
1 . 全新运行pdm run dev 正常
2.  后端编译pdm run build  正常
3.  把编译后的文件放入加上已存在的  data ，旧的流程可以显示，但是跑不了， 也不报错。
     已有的流程记录也无法打开查看。

**Comment by AndersonBY** [comment]
查一下 log 看看日志怎么写的

**Comment by suepradun** [comment]
2024-09-19 22:58:05,045 - Starting static file server at http://localhost:13286
2024-09-19 22:58:05,045 - WebSocket server started at ws://localhost:8765
2024-09-19 22:58:05,046 - Qdrant task server started.
2024-09-19 22:58:05,046 - Background task server 0 started.
2024-09-19 22:58:05,047 - Background task server 1 started.
2024-09-19 22:58:05,047 - Workflow task server started.
2024-09-19 22:58:05,048 - TTSServer is running
2024-09-19 22:58:05,174 - Debug: False
2024-09-19 22:58:05,174 - Version: 0.2.10
2024-09-19 23:07:49,785 - Task b66d02a767a64d3c833c89b5f340a79c update_workflow_tool_call_data added to queue.
2024-09-19 23:08:05,095 - Traceback (most recent call last):
  File "httpx\_transports\default.py", line 72, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 236, in handle_request
  File "httpcore\_sync\connection_pool.py", line 216, in handle_request
  File "httpcore\_sync\connection_pool.py", line 196, in handle_request
  File "httpcore\_sync\http_proxy.py", line 317, in handle_request
  File "httpcore\_sync\http11.py", line 383, in start_tls
  File "httpcore\_backends\sync.py", line 152, in start_tls
  File "contextlib.py", line 158, in __exit__
  File "httpcore\_exceptions.py", line 14, in map_exceptions
httpcore.ConnectTimeout: _ssl.c:989: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "openai\_base_client.py", line 973, in _request
  File "httpx\_client.py", line 926, in send
  File "httpx\_client.py", line 954, in _send_handling_auth
  File "httpx\_client.py", line 991, in _send_handling_redirects
  File "httpx\_client.py", line 1027, in _send_single_request
  File "httpx\_transports\default.py", line 235, in handle_request
  File "contextlib.py", line 158, in __exit__
  File "httpx\_transports\default.py", line 89, in map_httpcore_exceptions
httpx.ConnectTimeout: _ssl.c:989: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "background_task\server.py", line 65, in run
  File "background_task\tasks.py", line 74, in update_workflow_tool_call_data
  File "utilities\ai_utils\agent.py", line 63, in update_title
  File "vectorvein\chat_clients\openai_compatible_client.py", line 124, in create_completion
    response: ChatCompletion | Stream[ChatCompletionChunk] = self.raw_client.chat.completions.create(
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "openai\_utils\_utils.py", line 274, in wrapper
  File "openai\resources\chat\completions.py", line 704, in create
  File "openai\_base_client.py", line 1260, in post
  File "openai\_base_client.py", line 937, in request
  File "openai\_base_client.py", line 997, in _request
  File "openai\_base_client.py", line 1075, in _retry_request
  File "openai\_base_client.py", line 982, in _request
  File "openai\_base_client.py", line 1075, in _retry_request
  File "openai\_base_client.py", line 992, in _request
openai.APITimeoutError: Request timed out.

2024-09-19 23:08:05,095 - Error running task update_workflow_tool_call_data in worker 1: Request timed out.
2024-09-19 23:10:15,277 - Stopping background task server...
2024-09-19 23:27:36,761 - Starting static file server at http://localhost:13286
2024-09-19 23:27:36,762 - WebSocket server started at ws://localhost:8765
2024-09-19 23:27:36,762 - Qdrant task server started.
2024-09-19 23:27:36,763 - Background task server 1 started.
2024-09-19 23:27:36,763 - Background task server 0 started.
2024-09-19 23:27:36,763 - Workflow task server started.
2024-09-19 23:27:36,864 - TTSServer is running
2024-09-19 23:27:36,864 - Debug: False
2024-09-19 23:27:36,865 - Version: 0.2.10
2024-09-19 23:29:06,284 - Stopping background task server...

**Comment by AndersonBY** [comment]
AI 类节点超时了，建议你重新检查一下配置里的 API 端点信息，新结构迁移的时候可能没成功。

**Comment by suepradun** [comment]
端点删不掉。  删除后，再进入设置界面，又显示回原来的内容。

**Comment by suepradun** [comment]
使用debug，  显示的错误是，缺少workflow_version字段。
![image](https://github.com/user-attachments/assets/2e2a4eb5-c4b4-4d4d-93f9-a3a872ccf1a1)

**Comment by suepradun** [comment]
> 那是没有正确迁移数据库，得用0.2.10版本在原数据上运行来进行数据库迁移。

这个正确的操作步骤是什么？ 我现在是把旧的data目录拷贝入新打包出来的dist目录运行。
另外没有发现升级程序有日志输出，怎么能够确认升级部分有没执行完毕？

**Comment by WyInnovate** [comment]
毕总，我也想知道，怎么从0.2.9迁移到0.2.10，保留原先的运行记录、工作流，之前直接复制my_database就行，现在咋搞
@AndersonBY

**Comment by AndersonBY** [comment]
重新打包了 v0.2.10 了，可以重新下载尝试一下，迁移文件现在应该正常复制过去了。

**Comment by suepradun** [comment]
我发现备份老的库的 workflow表是异常的，连我想把表删除重建都不行。
我不确定是个案还是都会遇到，现在只能找工具把workflow数据导出来再处理。
![表异常](https://github.com/user-attachments/assets/73046c0d-abfb-495e-97d9-885699834745)

**Comment by AndersonBY** [comment]
理论上你用最新的 v0.2.10 把 data 文件夹放到程序目录下，启动程序将自动迁移了不用手动操作。

**Comment by suepradun** [comment]
> 理论上你用最新的 v0.2.10 把 data 文件夹放到程序目录下，启动程序将自动迁移了不用手动操作。

不明白为何自动不行， 已通过手工升级数据库表结构解决。

**Comment by WyInnovate** [comment]
试了下0.2.11 把 data 文件夹放到程序目录下，启动失败
我试一下新的0.2.10
报错内容如下：
```
Traceback (most recent call last):
  File "peewee.py", line 3322, in execute_sql
sqlite3.OperationalError: duplicate column name: tool_call_data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 210, in <module>
  File "main.py", line 65, in main
  File "models\base.py", line 79, in run_migrations
  File "peewee_migrate\router.py", line 229, in run
  File "peewee_migrate\router.py", line 200, in run_one
  File "peewee_migrate\migrator.py", line 76, in __call__
  File "playhouse\migrate.py", line 162, in run
  File "playhouse\migrate.py", line 156, in _handle_result
  File "playhouse\migrate.py", line 153, in _handle_result
  File "playhouse\migrate.py", line 162, in run
  File "playhouse\migrate.py", line 151, in _handle_result
  File "playhouse\migrate.py", line 147, in execute
  File "peewee.py", line 3330, in execute
  File "peewee.py", line 3320, in execute_sql
  File "peewee.py", line 3088, in __exit__
  File "peewee.py", line 196, in reraise
  File "peewee.py", line 3322, in execute_sql
peewee.OperationalError: duplicate column name: tool_call_data
```

**Comment by AndersonBY** [comment]
@WyInnovate 更新了代码，在 backend 目录下执行：

```
pdm run python .\migrations\migrate.py
```

输入数据库文件完整路径，可以自动修复迁移。
