### ISSUE TITLE
添加数据报错

### ISSUE THREAD

**Issue by zhaobingchun** [AndersonBY/vector-vein#7]
2023-05-27 13:17:56,788 - main_worker error: Unknown encoding cl100k_base
2023-05-27 13:17:56,788 - error_task: add_data
2023-05-27 13:17:56,788 - error_module: vector_db
2023-05-27 13:18:35,868 - vector_database receive request delete_point
2023-05-27 13:18:37,430 - vector_database receive request delete_point
2023-05-27 13:18:38,757 - vector_database receive request delete_point
2023-05-27 13:18:40,279 - vector_database receive request delete_point
2023-05-27 13:18:51,051 - worker receive task
2023-05-27 13:18:51,059 - Traceback (most recent call last):
  File "worker\__init__.py", line 75, in main_worker
  File "worker\tasks\__init__.py", line 36, in __call__
  File "worker\tasks\__init__.py", line 33, in __call__
  File "worker\tasks\__init__.py", line 15, in __call__
  File "worker\tasks\vector_db.py", line 45, in add_data
  File "utilities\text_splitter.py", line 200, in __init__
  File "tiktoken\model.py", line 75, in encoding_for_model
  File "tiktoken\registry.py", line 60, in get_encoding
ValueError: Unknown encoding cl100k_base

**Comment by AndersonBY** [comment]
根据搜索结果可能是这个问题：[https://github.com/openai/tiktoken/issues/43](https://github.com/openai/tiktoken/issues/43)
我更新了一下.spec文件里的hidden_import，可以重新build一下看看
