### ISSUE TITLE
bing search 失效

### ISSUE THREAD

**Issue by suepradun** [AndersonBY/vector-vein#72]
![image](https://github.com/user-attachments/assets/f99e23a8-a10d-472c-945b-b3fa48654b58)

worker.tasks.TaskError: 'webPages'
  File "worker\tasks\__init__.py", line 92, in __call__
  File "worker\__init__.py", line 251, in run_task
  File "worker\__init__.py", line 263, in run
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

KeyError: 'webPages'
  File "worker\tasks\tools.py", line 388, in handle_bing_results
  File "worker\tasks\tools.py", line 423, in text_search
  File "worker\tasks\__init__.py", line 104, in wrapper
  File "worker\tasks\__init__.py", line 43, in __call__
  File "worker\tasks\__init__.py", line 82, in __call__
2024-10-18 22:12:00,321 - [Workflow Task Server] Traceback (most recent call last):
2024-10-18 22:11:57,908 - [Workflow Task Server] Worker 1 received workflow request.
low_tool_call_data completed in worker 0.
2024-10-18 22:13:09,576 - [Workflow Task Server] error_module: tools
2024-10-18 22:13:09,576 - [Workflow Task Server] workflow worker error: 'webPages'

worker.tasks.TaskError: 'webPages'
  File "worker\tasks\__init__.py", line 92, in __call__
  File "worker\__init__.py", line 251, in run_task
  File "worker\__init__.py", line 263, in run
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

KeyError: 'webPages'
  File "worker\tasks\tools.py", line 388, in handle_bing_results
  File "worker\tasks\tools.py", line 423, in text_search
  File "worker\tasks\__init__.py", line 104, in wrapper
  File "worker\tasks\__init__.py", line 43, in __call__
  File "worker\tasks\__init__.py", line 82, in __call__
2024-10-18 22:13:09,574 - [Workflow Task Server] Traceback (most recent call last):
2024-10-18 22:13:07,663 - [Workflow Task Server] Worker 0 received workflow request.
2024-10-18 22:12:57,092 - [Shortcut Listener] Stopped.

**Comment by AndersonBY** [comment]
我这边测试正常，你确定设置里填了 Bing 搜索的 API KEY 了吗？

**Comment by suepradun** [comment]
我在测试页面及本地命令行都是ok的。
调用的endpoint 是 https://api.bing.microsoft.com/v7.0/custom/search

![image](https://github.com/user-attachments/assets/deaa0465-0e8d-4e81-911c-470d21247192)

**Comment by AndersonBY** [comment]
我这里用的 endpoint 是没有那个 custom 的，用的 Azure 的

https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/reference/endpoints

下个版本我加上可更改的 endpoint 配置。

**Comment by suepradun** [comment]
又换了一个在下面能跑通的key，但是在平台里还是不能用。奇怪。

curl --header "Ocp-Apim-Subscription-Key: <key>" "https://api.bing.microsoft.com/v7.0/search?q=AI&mkt=zh-CN"

**Comment by AndersonBY** [comment]
https://github.com/AndersonBY/vector-vein/releases/tag/v0.3.3
最新版增加了 Bing 搜索的端点配置，试一下你的端点是否能用。

**Comment by suepradun** [comment]
测试通过。
