### ISSUE TITLE
请问一下，这个可以开源代码可以搭建一个服务器版本吗？就是类似官网的体验页面的，可以通过浏览器访问的版本

### ISSUE THREAD

**Issue by devin-ma** [AndersonBY/vector-vein#8]
请问一下，这个可以开源代码可以搭建一个服务器版本吗？就是类似官网的体验页面的，可以通过浏览器访问的版本
可以启动一个web服务吗？而不是启动一个本地的exe程序？

**Comment by AndersonBY** [comment]
目前开源的代码是专门针对PC端个人使用场景的，暂时没有开源SaaS版的打算。

**Comment by AndersonBY** [comment]
大概率是因为没有webview2，可以从[这里安装](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)

**Comment by devin-ma** [comment]
安装 web view2，提示已经安装过了

![image](https://github.com/AndersonBY/vector-vein/assets/135328843/16d4823c-55ee-4917-ac66-2a489d4d8782)

**Comment by devin-ma** [comment]
尝试下载 0.0.5版本，启动报错：
![image](https://github.com/AndersonBY/vector-vein/assets/135328843/9d122f40-f1f1-4f5a-8338-3601b203cc70)

**Comment by AndersonBY** [comment]
完整的报错信息粘贴一下

**Comment by devin-ma** [comment]
Traceback (most recent call last):
  File "main.py", line 108, in <module>
  File "webview\__init__.py", line 132, in start
  File "webview\guilib.py", line 101, in initialize
  File "webview\guilib.py", line 62, in try_import
  File "webview\guilib.py", line 52, in import_winforms
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "webview\platforms\winforms.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 64, in __call__
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

**Comment by AndersonBY** [comment]
检查一下是不是放在了中文路径？

**Comment by devin-ma** [comment]
![image](https://github.com/AndersonBY/vector-vein/assets/135328843/189402e2-7478-4a1d-97c6-86d8f25732a9)
没有中文路径，在D盘，project
